### ISSUE TITLE
ds002338-fmriprep: MyMatrix.cpp: the QR iteration failed, but the last 0 eigenvalues may be correct

### ISSUE THREAD

**Issue by jbwexler** [poldracklab/tacc-openneuro#13]
Only for sub-xp213:

> MRItoBSpline degree 3
> MRItoBSpline degree 3
> MRItoBSpline degree 3
> MRItoBSpline degree 3
> 
>    - Max Resolution used: 0
>      -- gpS ( 106 , 106 , 33 )
>      -- gpT ( 106 , 106 , 33 )
>    - running loop to estimate saturation parameter:
> 
>    - Max Resolution used: 0
>      -- gpS ( 106 , 106 , 33 )
>      -- gpT ( 106 , 106 , 33 )
>    - running loop to estimate saturation parameter:
> 
>    - Max Resolution used: 0
>      -- gpS ( 106 , 106 , 33 )
>      -- gpT ( 106 , 106 , 33 )
>    - running loop to estimate saturation parameter:
> 
>    - Max Resolution used: 0
>      -- gpS ( 106 , 106 , 33 )
>      -- gpT ( 106 , 106 , 33 )
>    - running loop to estimate saturation parameter:
> Standard error:
> MyMatrix.cpp: info = 4, something went wrong:
> MyMatrix.cpp: the QR iteration failed, but the last 0 eigenvalues may be correct
> mri_robust_template: MyMatrix.cpp:1807: static void MyMatrix::SchurComplex(const vnl_matrix<double>&,
>  vnl_matrix<std::complex<double> >&, vnl_matrix<std::complex<double> >&): Assertion `info==0' failed.
> Aborted
> Return code: 134

**Comment by jbwexler** [comment]
Node: fmriprep_wf.single_subject_xp213_wf.syn_preprocessing_auto_00000.epi_reference_wf.epi_merge
Working directory: /scratch1/03201/jbwexler/work_dir/fmriprep/ds002338_sub-xp213/fmriprep_wf/single_subject_x
p213_wf/syn_preprocessing_auto_00000/epi_reference_wf/epi_merge

**Comment by jbwexler** [comment]
> Node: fmriprep_wf.single_subject_xp213_wf.syn_preprocessing_auto_00000.epi_reference_wf.epi_merge
> Working directory: /scratch1/03201/jbwexler/work_dir/fmriprep/ds002338_sub-xp213/fmriprep_wf/single_subject_xp213_wf/syn_preprocessing_auto_00000/epi_reference_wf/epi_merge
> 
> Node inputs:
> 
> args = <undefined>
> auto_detect_sensitivity = True
> average_metric = <undefined>
> environ = {'SUBJECTS_DIR': '/opt/freesurfer/subjects', 'OMP_NUM_THREADS': '1'}
> fixed_timepoint = True
> in_files = <undefined>
> in_intensity_scales = <undefined>
> initial_timepoint = 1
> initial_transforms = <undefined>
> intensity_scaling = True
> no_iteration = True
> num_threads = 1
> out_file = mri_robust_template_out.mgz
> outlier_sensitivity = <undefined>
> scaled_intensity_outputs = <undefined>
> subjects_dir = /opt/freesurfer/subjects
> subsample_threshold = 200
> transform_outputs = True
> 
> Traceback (most recent call last):
>   File "/opt/conda/lib/python3.8/site-packages/nipype/pipeline/plugins/multiproc.py", line 67, in run_node
>     result["result"] = node.run(updatehash=updatehash)
>   File "/opt/conda/lib/python3.8/site-packages/nipype/pipeline/engine/nodes.py", line 516, in run
>     result = self._run_interface(execute=True)
>   File "/opt/conda/lib/python3.8/site-packages/nipype/pipeline/engine/nodes.py", line 635, in _run_interface
>     return self._run_command(execute)
>   File "/opt/conda/lib/python3.8/site-packages/nipype/pipeline/engine/nodes.py", line 741, in _run_command
>     result = self._interface.run(cwd=outdir)
>   File "/opt/conda/lib/python3.8/site-packages/nipype/interfaces/freesurfer/base.py", line 264, in run
>     return super(FSCommandOpenMP, self).run(**inputs)
>   File "/opt/conda/lib/python3.8/site-packages/nipype/interfaces/freesurfer/base.py", line 149, in run
>     return super(FSCommand, self).run(**inputs)
>   File "/opt/conda/lib/python3.8/site-packages/nipype/interfaces/base/core.py", line 428, in run
>     runtime = self._run_interface(runtime)
>   File "/opt/conda/lib/python3.8/site-packages/nipype/interfaces/base/core.py", line 822, in _run_interface
>     self.raise_exception(runtime)
>   File "/opt/conda/lib/python3.8/site-packages/nipype/interfaces/base/core.py", line 749, in raise_exception
>     raise RuntimeError(
> RuntimeError: Command:
> mri_robust_template --satit --fixtp --mov /scratch1/03201/jbwexler/work_dir/fmriprep/ds002338_sub-xp213/fmriprep_wf/single_subject_xp213_wf/syn_preprocessing_auto_00000/epi_reference_wf/clip_bg_noise/mapflow/_clip_bg_noise0/clipped.nii.gz /scratch1/03201/jbwexler/work_dir/fmriprep/ds002338_sub-xp213/fmriprep_wf/single_subject_xp213_wf/syn_preprocessing_auto_00000/epi_reference_wf/clip_bg_noise/mapflow/_clip_bg_noise1/clipped.nii.gz /scratch1/03201/jbwexler/work_dir/fmriprep/ds002338_sub-xp213/fmriprep_wf/single_subject_xp213_wf/syn_preprocessing_auto_00000/epi_reference_wf/clip_bg_noise/mapflow/_clip_bg_noise2/clipped.nii.gz /scratch1/03201/jbwexler/work_dir/fmriprep/ds002338_sub-xp213/fmriprep_wf/single_subject_xp213_wf/syn_preprocessing_auto_00000/epi_reference_wf/clip_bg_noise/mapflow/_clip_bg_noise3/clipped.nii.gz /scratch1/03201/jbwexler/work_dir/fmriprep/ds002338_sub-xp213/fmriprep_wf/single_subject_xp213_wf/syn_preprocessing_auto_00000/epi_reference_wf/clip_bg_noise/mapflow/_clip_bg_noise4/clipped.nii.gz --inittp 1 --iscale --noit --template mri_robust_template_out.mgz --subsample 200 --lta /scratch1/03201/jbwexler/work_dir/fmriprep/ds002338_sub-xp213/fmriprep_wf/single_subject_xp213_wf/syn_preprocessing_auto_00000/epi_reference_wf/epi_merge/tp1.lta /scratch1/03201/jbwexler/work_dir/fmriprep/ds002338_sub-xp213/fmriprep_wf/single_subject_xp213_wf/syn_preprocessing_auto_00000/epi_reference_wf/epi_merge/tp2.lta /scratch1/03201/jbwexler/work_dir/fmriprep/ds002338_sub-xp213/fmriprep_wf/single_subject_xp213_wf/syn_preprocessing_auto_00000/epi_reference_wf/epi_merge/tp3.lta /scratch1/03201/jbwexler/work_dir/fmriprep/ds002338_sub-xp213/fmriprep_wf/single_subject_xp213_wf/syn_preprocessing_auto_00000/epi_reference_wf/epi_merge/tp4.lta /scratch1/03201/jbwexler/work_dir/fmriprep/ds002338_sub-xp213/fmriprep_wf/single_subject_xp213_wf/syn_preprocessing_auto_00000/epi_reference_wf/epi_merge/tp5.lta
> Standard output:
> $Id: mri_robust_template.cpp,v 1.54 2016/05/05 21:17:08 mreuter Exp $
> 
> --satit: Will estimate SAT iteratively!
> --fixtp: Will map everything to init TP!
> --mov: Using /scratch1/03201/jbwexler/work_dir/fmriprep/ds002338_sub-xp213/fmriprep_wf/single_subject_xp213_wf/syn_preprocessing_auto_00000/epi_reference_wf/clip_bg_noise/mapflow/_clip_bg_noise0/clipped.nii.gz as movable/source volume.
> --mov: Using /scratch1/03201/jbwexler/work_dir/fmriprep/ds002338_sub-xp213/fmriprep_wf/single_subject_xp213_wf/syn_preprocessing_auto_00000/epi_reference_wf/clip_bg_noise/mapflow/_clip_bg_noise1/clipped.nii.gz as movable/source volume.
> --mov: Using /scratch1/03201/jbwexler/work_dir/fmriprep/ds002338_sub-xp213/fmriprep_wf/single_subject_xp213_wf/syn_preprocessing_auto_00000/epi_reference_wf/clip_bg_noise/mapflow/_clip_bg_noise2/clipped.nii.gz as movable/source volume.
> --mov: Using /scratch1/03201/jbwexler/work_dir/fmriprep/ds002338_sub-xp213/fmriprep_wf/single_subject_xp213_wf/syn_preprocessing_auto_00000/epi_reference_wf/clip_bg_noise/mapflow/_clip_bg_noise3/clipped.nii.gz as movable/source volume.
> --mov: Using /scratch1/03201/jbwexler/work_dir/fmriprep/ds002338_sub-xp213/fmriprep_wf/single_subject_xp213_wf/syn_preprocessing_auto_00000/epi_reference_wf/clip_bg_noise/mapflow/_clip_bg_noise4/clipped.nii.gz as movable/source volume.
>     Total: 5 input volumes
> --inittp: Using TP 1 as target for initialization
> --iscale: Enableing intensity scaling!
> --noit: Will output only first template (no iterations)!
> --template: Using mri_robust_template_out.mgz as template output volume.
> --subsample: Will subsample if size is larger than 200 on all axes!
> --lta: Will output LTA transforms
> Setting iscale ...
> reading source '/scratch1/03201/jbwexler/work_dir/fmriprep/ds002338_sub-xp213/fmriprep_wf/single_subject_xp213_wf/syn_preprocessing_auto_00000/epi_reference_wf/clip_bg_noise/mapflow/_clip_bg_noise0/clipped.nii.gz'...
> converting source '/scratch1/03201/jbwexler/work_dir/fmriprep/ds002338_sub-xp213/fmriprep_wf/single_subject_xp213_wf/syn_preprocessing_auto_00000/epi_reference_wf/clip_bg_noise/mapflow/_clip_bg_noise0/clipped.nii.gz' to bspline ...
> MRItoBSpline degree 3
> reading source '/scratch1/03201/jbwexler/work_dir/fmriprep/ds002338_sub-xp213/fmriprep_wf/single_subject_xp213_wf/syn_preprocessing_auto_00000/epi_reference_wf/clip_bg_noise/mapflow/_clip_bg_noise1/clipped.nii.gz'...
> converting source '/scratch1/03201/jbwexler/work_dir/fmriprep/ds002338_sub-xp213/fmriprep_wf/single_subject_xp213_wf/syn_preprocessing_auto_00000/epi_reference_wf/clip_bg_noise/mapflow/_clip_bg_noise1/clipped.nii.gz' to bspline ...
> MRItoBSpline degree 3
> reading source '/scratch1/03201/jbwexler/work_dir/fmriprep/ds002338_sub-xp213/fmriprep_wf/single_subject_xp213_wf/syn_preprocessing_auto_00000/epi_reference_wf/clip_bg_noise/mapflow/_clip_bg_noise2/clipped.nii.gz'...
> converting source '/scratch1/03201/jbwexler/work_dir/fmriprep/ds002338_sub-xp213/fmriprep_wf/single_subject_xp213_wf/syn_preprocessing_auto_00000/epi_reference_wf/clip_bg_noise/mapflow/_clip_bg_noise2/clipped.nii.gz' to bspline ...
> MRItoBSpline degree 3
> reading source '/scratch1/03201/jbwexler/work_dir/fmriprep/ds002338_sub-xp213/fmriprep_wf/single_subject_xp213_wf/syn_preprocessing_auto_00000/epi_reference_wf/clip_bg_noise/mapflow/_clip_bg_noise3/clipped.nii.gz'...
> converting source '/scratch1/03201/jbwexler/work_dir/fmriprep/ds002338_sub-xp213/fmriprep_wf/single_subject_xp213_wf/syn_preprocessing_auto_00000/epi_reference_wf/clip_bg_noise/mapflow/_clip_bg_noise3/clipped.nii.gz' to bspline ...
> MRItoBSpline degree 3
> reading source '/scratch1/03201/jbwexler/work_dir/fmriprep/ds002338_sub-xp213/fmriprep_wf/single_subject_xp213_wf/syn_preprocessing_auto_00000/epi_reference_wf/clip_bg_noise/mapflow/_clip_bg_noise4/clipped.nii.gz'...
> converting source '/scratch1/03201/jbwexler/work_dir/fmriprep/ds002338_sub-xp213/fmriprep_wf/single_subject_xp213_wf/syn_preprocessing_auto_00000/epi_reference_wf/clip_bg_noise/mapflow/_clip_bg_noise4/clipped.nii.gz' to bspline ...
> MRItoBSpline degree 3
> 
> MultiRegistration::initializing Xforms (init 1 , maxres 0 , iterate 5 , epsit 0.01 ) :
> 
> [init] ========================= TP 5 to TP 1 ==============================
>          Register TP 5 ( /scratch1/03201/jbwexler/work_dir/fmriprep/ds002338_sub-xp213/fmriprep_wf/single_subject_xp213_wf/syn_preprocessing_auto_00000/epi_reference_wf/clip_bg_noise/mapflow/_clip_bg_noise4/clipped.nii.gz )
>           to      TP 1 ( /scratch1/03201/jbwexler/work_dir/fmriprep/ds002338_sub-xp213/fmriprep_wf/single_subject_xp213_wf/syn_preprocessing_auto_00000/epi_reference_wf/clip_bg_noise/mapflow/_clip_bg_noise0/clipped.nii.gz )
> 
> 
> [init] ========================= TP 2 to TP 1 ==============================
>          Register TP 2 ( /scratch1/03201/jbwexler/work_dir/fmriprep/ds002338_sub-xp213/fmriprep_wf/single_subject_xp213_wf/syn_preprocessing_auto_00000/epi_reference_wf/clip_bg_noise/mapflow/_clip_bg_noise1/clipped.nii.gz )
>           to      TP 1 ( /scratch1/03201/jbwexler/work_dir/fmriprep/ds002338_sub-xp213/fmriprep_wf/single_subject_xp213_wf/syn_preprocessing_auto_00000/epi_reference_wf/clip_bg_noise/mapflow/_clip_bg_noise0/clipped.nii.gz )
> 
> 
> [init] ========================= TP 3 to TP 1 ==============================
>          Register TP 3 ( /scratch1/03201/jbwexler/work_dir/fmriprep/ds002338_sub-xp213/fmriprep_wf/single_subject_xp213_wf/syn_preprocessing_auto_00000/epi_reference_wf/clip_bg_noise/mapflow/_clip_bg_noise2/clipped.nii.gz )
>           to      TP 1 ( /scratch1/03201/jbwexler/work_dir/fmriprep/ds002338_sub-xp213/fmriprep_wf/single_subject_xp213_wf/syn_preprocessing_auto_00000/epi_reference_wf/clip_bg_noise/mapflow/_clip_bg_noise0/clipped.nii.gz )
> 
> 
> [init] ========================= TP 4 to TP 1 ==============================
>          Register TP 4 ( /scratch1/03201/jbwexler/work_dir/fmriprep/ds002338_sub-xp213/fmriprep_wf/single_subject_xp213_wf/syn_preprocessing_auto_00000/epi_reference_wf/clip_bg_noise/mapflow/_clip_bg_noise3/clipped.nii.gz )
>           to      TP 1 ( /scratch1/03201/jbwexler/work_dir/fmriprep/ds002338_sub-xp213/fmriprep_wf/single_subject_xp213_wf/syn_preprocessing_auto_00000/epi_reference_wf/clip_bg_noise/mapflow/_clip_bg_noise0/clipped.nii.gz )
> 
>        -- Original : (1.98113, 1.98113, 4)mm and (106, 106, 16) voxels.
>        -- Resampled: (1.98113, 1.98113, 1.98113)mm and (106, 106, 33) voxels.
>        -- Reslicing using        -- Original : (1.98113, 1.98113, 4)mm and (106, 106, 16) voxels.
> cubic bspline
>        -- Resampled: (1.98113, 1.98113, 1.98113)mm and (106, 106, 33) voxels.
>        -- Reslicing using cubic bspline
>        -- Original : (1.98113, 1.98113, 4)mm and (106, 106, 16) voxels.
>        -- Resampled: (1.98113, 1.98113, 1.98113)mm and (106, 106, 33) voxels.
>        -- Reslicing using cubic bspline
>        -- Original : (1.98113, 1.98113, 4)mm and (106, 106, 16) voxels.
>        -- Resampled: (1.98113, 1.98113, 1.98113)mm and (106, 106, 33) voxels.
>        -- Reslicing using cubic bspline
> MRItoBSpline degree 3
> MRItoBSpline degree 3
> MRItoBSpline degree 3
> MRItoBSpline degree 3
>        -- Original : (1.98113, 1.98113, 4)mm and (106, 106, 16) voxels.
>        -- Resampled: (1.98113, 1.98113, 1.98113)mm and (106, 106, 33) voxels.
>        -- Reslicing using cubic bspline
>        -- Original : (1.98113, 1.98113, 4)mm and (106, 106, 16) voxels.
>        -- Resampled: (1.98113, 1.98113, 1.98113)mm and (106, 106, 33) voxels.
>        -- Reslicing using cubic bspline
>        -- Original : (1.98113, 1.98113, 4)mm and (106, 106, 16) voxels.
>        -- Resampled: (1.98113, 1.98113, 1.98113)mm and (106, 106, 33) voxels.
>        -- Reslicing using cubic bspline
>        -- Original : (1.98113, 1.98113, 4)mm and (106, 106, 16) voxels.
>        -- Resampled: (1.98113, 1.98113, 1.98113)mm and (106, 106, 33) voxels.
>        -- Reslicing using cubic bspline
> MRItoBSpline degree 3
> MRItoBSpline degree 3
> MRItoBSpline degree 3
> MRItoBSpline degree 3
> 
>    - Max Resolution used: 0
>      -- gpS ( 106 , 106 , 33 )
>      -- gpT ( 106 , 106 , 33 )
>    - running loop to estimate saturation parameter:
> 
>    - Max Resolution used: 0
>      -- gpS ( 106 , 106 , 33 )
>      -- gpT ( 106 , 106 , 33 )
>    - running loop to estimate saturation parameter:
> 
>    - Max Resolution used: 0
>      -- gpS ( 106 , 106 , 33 )
>      -- gpT ( 106 , 106 , 33 )
>    - running loop to estimate saturation parameter:
> 
>    - Max Resolution used: 0
>      -- gpS ( 106 , 106 , 33 )
>      -- gpT ( 106 , 106 , 33 )
>    - running loop to estimate saturation parameter:
> Standard error:
> MyMatrix.cpp: info = 4, something went wrong:
> MyMatrix.cpp: the QR iteration failed, but the last 0 eigenvalues may be correct
> mri_robust_template: MyMatrix.cpp:1807: static void MyMatrix::SchurComplex(const vnl_matrix<double>&, vnl_matrix<std::complex<double> >&, vnl_matrix<std::complex<double> >&): Assertion `info==0' failed.
> Aborted
> Return code: 134

**Comment by effigies** [comment]
Rerunning will probably help. Running this command locally did fine.

**Comment by jbwexler** [comment]
Solved with rerun.
