### ISSUE TITLE
ds002338-fmriprep: "Found usable B0-map (fieldmap) estimator(s) <auto_00000> to correct"

### ISSUE THREAD

**Issue by jbwexler** [poldracklab/tacc-openneuro#14]
Only for sub-xp210. The run exited immediately after this:

> 220501-13:08:50,551 nipype.workflow IMPORTANT:
>          Building fMRIPrep's workflow:
>            * BIDS dataset path: /scratch1/03201/jbwexler/openneuro_derivatives/derivatives/fmriprep/ds002338-fmriprep/sourcedata/raw.
>            * Participant list: ['xp210'].
>            * Run identifier: 20220501-130705_34309072-3c00-4451-aa52-f651e05c56f2.
>            * Output spaces: MNI152NLin2009cAsym:res-2 anat func fsaverage:den-10k.
>            * Pre-run FreeSurfer's SUBJECTS_DIR: /scratch1/03201/jbwexler/openneuro_derivatives/derivatives/fmriprep/ds002338-fmriprep/sourcedata/freesurfer.
> 220501-13:08:54,298 nipype.workflow INFO:
>          B0 field inhomogeneity map will be estimated with  the following 1 estimators: [<EstimatorType.ANAT: 5>].
> 220501-13:08:54,463 nipype.workflow INFO:
>          No single-band-reference found for sub-xp210_task-2dNF_run-01_bold.nii.gz.
> 220501-13:08:54,463 nipype.workflow INFO:
>          Found usable B0-map (fieldmap) estimator(s) <auto_00000> to correct </scratch1/03201/jbwexler/openneuro_derivatives/derivatives/fmriprep/ds002338-fmriprep/sourcedata/raw/sub-xp210/func/sub-xp210_task-2dNF_run-01_bold.nii.gz> for susceptibility-derived distortions.
> 220501-13:08:55,837 nipype.workflow INFO:
>          No single-band-reference found for sub-xp210_task-2dNF_run-02_bold.nii.gz.
> 220501-13:08:55,837 nipype.workflow INFO:
>          Found usable B0-map (fieldmap) estimator(s) <auto_00000> to correct </scratch1/03201/jbwexler/openneuro_derivatives/derivatives/fmriprep/ds002338-fmriprep/sourcedata/raw/sub-xp210/func/sub-xp210_task-2dNF_run-02_bold.nii.gz> for susceptibility-derived distortions.

**Comment by jbwexler** [comment]
> Process Process-2:
> Traceback (most recent call last):
>   File "/opt/conda/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
>     self.run()
>   File "/opt/conda/lib/python3.8/multiprocessing/process.py", line 108, in run
>     self._target(*self._args, **self._kwargs)
>   File "/opt/conda/lib/python3.8/site-packages/fmriprep/cli/workflow.py", line 118, in build_workflow
>     retval["workflow"] = init_fmriprep_wf()
>   File "/opt/conda/lib/python3.8/site-packages/fmriprep/workflows/base.py", line 85, in init_fmriprep_wf
>     single_subject_wf = init_single_subject_wf(subject_id)
>   File "/opt/conda/lib/python3.8/site-packages/fmriprep/workflows/base.py", line 370, in init_single_subject_wf
>     func_preproc_wf = init_func_preproc_wf(bold_file, has_fieldmap=has_fieldmap)
>   File "/opt/conda/lib/python3.8/site-packages/fmriprep/workflows/bold/base.py", line 167, in init_func_preproc_wf
>     if nb.load(
>   File "/opt/conda/lib/python3.8/site-packages/nibabel/loadsave.py", line 55, in load
>     raise ImageFileError(f'Cannot work out file type of "{filename}"')
> nibabel.filebasedimages.ImageFileError: Cannot work out file type of "/scratch1/03201/jbwexler/openneuro_derivatives/derivatives/fmriprep/ds002338-fmriprep/sourcedata/raw/sub-xp210/func/sub-xp210_task-2dNF_run-03_bold.nii.gz"
> ...skipping...
> Process Process-2:
> Traceback (most recent call last):
>   File "/opt/conda/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
>     self.run()
>   File "/opt/conda/lib/python3.8/multiprocessing/process.py", line 108, in run
>     self._target(*self._args, **self._kwargs)
>   File "/opt/conda/lib/python3.8/site-packages/fmriprep/cli/workflow.py", line 118, in build_workflow
>     retval["workflow"] = init_fmriprep_wf()
>   File "/opt/conda/lib/python3.8/site-packages/fmriprep/workflows/base.py", line 85, in init_fmriprep_wf
>     single_subject_wf = init_single_subject_wf(subject_id)
>   File "/opt/conda/lib/python3.8/site-packages/fmriprep/workflows/base.py", line 370, in init_single_subject_wf
>     func_preproc_wf = init_func_preproc_wf(bold_file, has_fieldmap=has_fieldmap)
>   File "/opt/conda/lib/python3.8/site-packages/fmriprep/workflows/bold/base.py", line 167, in init_func_preproc_wf
>     if nb.load(
>   File "/opt/conda/lib/python3.8/site-packages/nibabel/loadsave.py", line 55, in load
>     raise ImageFileError(f'Cannot work out file type of "{filename}"')
> nibabel.filebasedimages.ImageFileError: Cannot work out file type of "/scratch1/03201/jbwexler/openneuro_derivatives/derivatives/fmriprep/ds002338-fmriprep/sourcedata/raw/sub-xp210/func/sub-xp210_task-2dNF_run-03_bold.nii.gz"

**Comment by effigies** [comment]
Looks like a failure to `datalad get`. I'm able to fetch and load this file in nibabel locally.

**Comment by jbwexler** [comment]
Rerunning didn't fix. My script should be datalad getting but going to do this manually and rerun another time just in case.
