### ISSUE TITLE
ds002322-fmriprep: "Segmentation fault      ${FSLDIR}/bin/bet2 $IN $OUT $bet2opts"

### ISSUE THREAD

**Issue by jbwexler** [poldracklab/tacc-openneuro#15]
Only happened for sub-45.

> Node: fmriprep_wf.single_subject_45_wf.func_preproc_task_alice_echo_2_wf.final_boldref_wf.enhance
> _and_skullstrip_bold_wf.skullstrip_first_pass
> Working directory: /scratch1/03201/jbwexler/work_dir/fmriprep/ds002322_sub-45/fmriprep_wf/single_
> subject_45_wf/func_preproc_task_alice_echo_2_wf/final_boldref_wf/enhance_and_skullstrip_bold_wf/s
> kullstrip_first_pass
> 
> Node inputs:
> 
> args = <undefined>
> center = <undefined>
> environ = {'FSLOUTPUTTYPE': 'NIFTI_GZ'}
> frac = 0.2
> functional = <undefined>
> in_file = <undefined>
> mask = True
> mesh = <undefined>
> no_output = <undefined>
> out_file = <undefined>
> outline = <undefined>
> output_type = NIFTI_GZ
> padding = <undefined>
> radius = <undefined>
> reduce_bias = <undefined>
> remove_eyes = <undefined>
> robust = <undefined>
> skull = <undefined>
> surfaces = <undefined>
> t2_guided = <undefined>
> threshold = <undefined>
> vertical_gradient = <undefined>
> 
> Traceback (most recent call last):
>   File "/opt/conda/lib/python3.8/site-packages/nipype/pipeline/plugins/multiproc.py", line 67, in run_node
>     result["result"] = node.run(updatehash=updatehash)
>   File "/opt/conda/lib/python3.8/site-packages/nipype/pipeline/engine/nodes.py", line 516, in run
>     result = self._run_interface(execute=True)
>   File "/opt/conda/lib/python3.8/site-packages/nipype/pipeline/engine/nodes.py", line 635, in _run_interface
>     return self._run_command(execute)
>   File "/opt/conda/lib/python3.8/site-packages/nipype/pipeline/engine/nodes.py", line 741, in _run_command
>     result = self._interface.run(cwd=outdir)
>   File "/opt/conda/lib/python3.8/site-packages/nipype/interfaces/base/core.py", line 428, in run
>     runtime = self._run_interface(runtime)
>   File "/opt/conda/lib/python3.8/site-packages/nipype/interfaces/fsl/preprocess.py", line 163, in
>  _run_interface
>     runtime = super(BET, self)._run_interface(runtime)
>   File "/opt/conda/lib/python3.8/site-packages/nipype/interfaces/base/core.py", line 822, in _run
> _interface
>     self.raise_exception(runtime)
>   File "/opt/conda/lib/python3.8/site-packages/nipype/interfaces/base/core.py", line 749, in rais
> e_exception
>     raise RuntimeError(
> RuntimeError: Command:
> bet vol0000_xform-00000_clipped_merged_average_corrected.nii.gz vol0000_xform-00000_clipped_merge
> d_average_corrected_brain.nii.gz -f 0.20 -m
> Standard output:
> /opt/fsl-6.0.5.1/bin/bet failed during command:vol0000_xform-00000_clipped_merged_average_correct
> ed.nii.gz vol0000_xform-00000_clipped_merged_average_corrected_brain.nii.gz -f 0.20 -m
> Standard error:
> /opt/fsl-6.0.5.1/bin/bet: line 399: 256984 Segmentation fault      ${FSLDIR}/bin/bet2 $IN $OUT $b
> et2opts
> Return code: 1

**Comment by effigies** [comment]
This was probably an out-of-memory error that was not caught by BET causing a null pointer dereference. Rerunning seems to have fixed it.
