### ISSUE TITLE
ds002422-fmriprep: ValueError: shape (64, 64, 33) for image 1 not compatible with first image shape (64, 64, 34) with axis == None

### ISSUE THREAD

**Issue by jbwexler** [poldracklab/tacc-openneuro#19]
Just for sub-20. Full error message:

> Node: fmriprep_wf.single_subject_20_wf.fmap_preproc_wf.wf_auto_00001.magnitude_wf.magmrg
> Working directory: /scratch1/03201/jbwexler/work_dir/fmriprep/ds002422_sub-20/fmriprep_wf/single_subject_20_wf/fmap_preproc_wf/wf_auto_00001/magnitude_wf/magmrg
> 
> Node inputs:
> 
> grand_mean_scaling = False
> hmc = False
> in_files = ['/scratch1/03201/jbwexler/openneuro_derivatives/derivatives/fmriprep/ds002422-fmriprep/sourcedata/raw/sub-20/fmap/sub-20_run-02_magnitude1.nii', '/scratch1/03201/jbwexler/openneuro_derivatives/derivatives/fmriprep/ds002422-fmriprep/sourcedata/raw/sub-20/fmap/sub-20_run-02_magnitude2.nii']
> in_mask = <undefined>
> to_ras = False
> zero_based_avg = True
> 
> Traceback (most recent call last):
>   File "/opt/conda/lib/python3.8/site-packages/nipype/pipeline/plugins/multiproc.py", line 67, in run_node
>     result["result"] = node.run(updatehash=updatehash)
>   File "/opt/conda/lib/python3.8/site-packages/nipype/pipeline/engine/nodes.py", line 516, in run
>     result = self._run_interface(execute=True)
>   File "/opt/conda/lib/python3.8/site-packages/nipype/pipeline/engine/nodes.py", line 635, in _run_interface
>     return self._run_command(execute)
>   File "/opt/conda/lib/python3.8/site-packages/nipype/pipeline/engine/nodes.py", line 741, in _run_command
>     result = self._interface.run(cwd=outdir)
>   File "/opt/conda/lib/python3.8/site-packages/nipype/interfaces/base/core.py", line 428, in run
>     runtime = self._run_interface(runtime)
>   File "/opt/conda/lib/python3.8/site-packages/niworkflows/interfaces/images.py", line 149, in _run_interface
>     filenii = nb.concat_images(nii_list)
>   File "/opt/conda/lib/python3.8/site-packages/nibabel/funcs.py", line 138, in concat_images
>     raise ValueError(f'shape {img.shape} for image {i} not compatible with '
> ValueError: shape (64, 64, 33) for image 1 not compatible with first image shape (64, 64, 34) with axis == None

**Comment by effigies** [comment]
Problem with dataset. We can open an issue on sdcflows in case this can be coped with, but not our problem for now.

**Comment by effigies** [comment]
Just to be clear, the inputs don't share a common shape:

```console
$ nib-ls *.nii
sub-20_run-01_magnitude1.nii uint16 [ 64,  64,  24] 3.59x3.59x3.30   sform
sub-20_run-01_magnitude2.nii uint16 [ 64,  64,  24] 3.59x3.59x3.30   sform
sub-20_run-01_phasediff.nii  uint16 [ 64,  64,  24] 3.59x3.59x3.30   sform
sub-20_run-02_magnitude1.nii uint16 [ 64,  64,  34] 3.59x3.59x3.78   sform
sub-20_run-02_magnitude2.nii uint16 [ 64,  64,  33] 3.59x3.59x3.78   sform
sub-20_run-02_phasediff.nii  uint16 [ 64,  64,  36] 3.59x3.59x3.78   sform
```

Handling this case would be a feature; rejecting it is not a bug. A better error message could probably be devised, though.
