### ISSUE TITLE
fmriprep/freesurfer can't open rh.cortex.label even though it exists

### ISSUE THREAD

**Issue by jbwexler** [poldracklab/tacc-openneuro#2]
I'm pretty sure this issue is being caused by the fact that I was accidentally copying links instead of the actual file when replacing missing fsaverage and fsaverage5 files. I'm testing now to see if this was the issue.

Here's the full output of an example crash file:

> (main) login4.frontera(1018)$ cat /scratch1/03201/jbwexler/openneuro_derivatives/derivatives/fmriprep/ds000117-fmriprep/sub-01/log/20220228-075311_fca40b24-c8f5-4e61-b877-cd051e4819d8/crash-20220228-091805-jbwexler-_sampler1-a2a7419f-2818-4d76-8b5d-7dc5640981f3.txt
> Node: _sampler1
> Working directory: /scratch1/03201/jbwexler/work_dir/fmriprep/ds000117_sub-01/fmriprep_wf/single_subject_01_wf/func_preproc_ses_mri_task_facerecognition_run_09_wf/bold_surf_wf/_target_fsaverage/sampler/mapflow/_sampler1
> 
> Node inputs:
> 
> apply_rot = <undefined>
> apply_trans = <undefined>
> args = <undefined>
> cortex_mask = True
> environ = {'SUBJECTS_DIR': '/opt/freesurfer/subjects'}
> fix_tk_reg = <undefined>
> float2int_method = <undefined>
> frame = <undefined>
> hemi = rh
> hits_file = <undefined>
> hits_type = <undefined>
> ico_order = <undefined>
> interp_method = trilinear
> mask_label = <undefined>
> mni152reg = <undefined>
> no_reshape = <undefined>
> out_file = <undefined>
> out_type = gii
> override_reg_subj = True
> projection_stem = <undefined>
> reference_file = <undefined>
> reg_file = /scratch1/03201/jbwexler/work_dir/fmriprep/ds000117_sub-01/fmriprep_wf/single_subject_01_wf/func_preproc_ses_mri_task_facerecognition_run_09_wf/bold_surf_wf/itk2lta/out.lta
> reg_header = <undefined>
> reshape = <undefined>
> reshape_slices = <undefined>
> sampling_method = average
> sampling_range = (0.0, 1.0, 0.2)
> sampling_units = frac
> scale_input = <undefined>
> smooth_surf = <undefined>
> smooth_vol = <undefined>
> source_file = /scratch1/03201/jbwexler/work_dir/fmriprep/ds000117_sub-01/fmriprep_wf/single_subject_01_wf/func_preproc_ses_mri_task_facerecognition_run_09_wf/bold_surf_wf/_target_fsaverage/rename_src/fsaverage.nii
> subject_id = sub-01
> subjects_dir = /scratch1/03201/jbwexler/openneuro_derivatives/derivatives/fmriprep/ds000117-fmriprep/sourcedata/freesurfer
> surf_reg = <undefined>
> surface = <undefined>
> target_subject = fsaverage
> vox_file = <undefined>
> 
> Traceback (most recent call last):
>   File "/opt/conda/lib/python3.8/site-packages/nipype/pipeline/plugins/multiproc.py", line 67, in run_node
>     result["result"] = node.run(updatehash=updatehash)
>   File "/opt/conda/lib/python3.8/site-packages/nipype/pipeline/engine/nodes.py", line 516, in run
>     result = self._run_interface(execute=True)
>   File "/opt/conda/lib/python3.8/site-packages/nipype/pipeline/engine/nodes.py", line 635, in _run_interface
>     return self._run_command(execute)
>   File "/opt/conda/lib/python3.8/site-packages/nipype/pipeline/engine/nodes.py", line 741, in _run_command
>     result = self._interface.run(cwd=outdir)
>   File "/opt/conda/lib/python3.8/site-packages/nipype/interfaces/freesurfer/base.py", line 149, in run
>     return super(FSCommand, self).run(**inputs)
>   File "/opt/conda/lib/python3.8/site-packages/nipype/interfaces/base/core.py", line 428, in run
>     runtime = self._run_interface(runtime)
>   File "/opt/conda/lib/python3.8/site-packages/nipype/interfaces/base/core.py", line 822, in _run_interface
>     self.raise_exception(runtime)
>   File "/opt/conda/lib/python3.8/site-packages/nipype/interfaces/base/core.py", line 749, in raise_exception
>     raise RuntimeError(
> RuntimeError: Command:
> mri_vol2surf --cortex --hemi rh --interp trilinear --o /scratch1/03201/jbwexler/work_dir/fmriprep/ds000117_sub-01/fmriprep_wf/single_subject_01_wf/func_preproc_ses_mri_task_facerecognition_run_09_wf/bold_surf_wf/_target_fsaverage/sampler/mapflow/_sampler1/rh.fsaverage.gii  --srcsubject sub-01 --reg /scratch1/03201/jbwexler/work_dir/fmriprep/ds000117_sub-01/fmriprep_wf/single_subject_01_wf/func_preproc_ses_mri_task_facerecognition_run_09_wf/bold_surf_wf/itk2lta/out.lta --projfrac-avg 0.000 1.000 0.200 --mov /scratch1/03201/jbwexler/work_dir/fmriprep/ds000117_sub-01/fmriprep_wf/single_subject_01_wf/func_preproc_ses_mri_task_facerecognition_run_09_wf/bold_surf_wf/_target_fsaverage/rename_src/fsaverage.nii --trgsubject fsaverage
> Standard output:
> srcvol = /scratch1/03201/jbwexler/work_dir/fmriprep/ds000117_sub-01/fmriprep_wf/single_subject_01_wf/func_preproc_ses_mri_task_facerecognition_run_09_wf/bold_surf_wf/_target_fsaverage/rename_src/fsaverage.nii
> srcreg = /scratch1/03201/jbwexler/work_dir/fmriprep/ds000117_sub-01/fmriprep_wf/single_subject_01_wf/func_preproc_ses_mri_task_facerecognition_run_09_wf/bold_surf_wf/itk2lta/out.lta
> srcregold = 0
> srcwarp unspecified
> surf = white
> hemi = rh
> trgsubject = fsaverage
> surfreg = sphere.reg
> ProjFrac = 0.5
> thickness = thickness
> reshape = 0
> interp = trilinear
> float2int = round
> GetProjMax = 0
> INFO: float2int code = 0
> niiRead(): NIFTI_UNITS_UNKNOWN, assuming mm
> Done loading volume
> INFO: overriding regsubject  with sub-01
> Input reg is LTA
> -------- original matrix -----------
> -1.00000   0.00042   0.00036  -0.11612;
>  0.00036   0.00031   1.00000   11.82422;
> -0.00042  -1.00000   0.00031  -17.68887;
>  0.00000   0.00000   0.00000   1.00000;
> -------- original matrix -----------
> Loading label /scratch1/03201/jbwexler/openneuro_derivatives/derivatives/fmriprep/ds000117-fmriprep/sourcedata/freesurfer/fsaverage/label/rh.cortex.label
> Standard error:
> No such file or directory
> mri_vol2surf: could not open label file /scratch1/03201/jbwexler/openneuro_derivatives/derivatives/fmriprep/ds000117-fmriprep/sourcedata/freesurfer/fsaverage/label/rh.cortex.label
> Invalid argument
> mri_vol2surf: could not load label file /scratch1/03201/jbwexler/openneuro_derivatives/derivatives/fmriprep/ds000117-fmriprep/sourcedata/freesurfer/fsaverage/label/rh.cortex.label
> Invalid argument
> Return code: 255

**Comment by effigies** [comment]
Probably need to datalad get...

**Comment by jbwexler** [comment]
They actually weren't annexed but were linked to files on corral. Kind of a long story how they ended up that way.
