### ISSUE TITLE
fMRIPrep 22.0.0 errors: Exception raised while executing Node _parcstats0

### ISSUE THREAD

**Issue by jbwexler** [poldracklab/tacc-openneuro#23]
I suddenly started getting this error for every subject of every dataset I run. It seems to have started once I switched to v22.0.0.

Also posted here: https://github.com/nipreps/fmriprep/issues/2832

> Node: _parcstats0
> Working directory: /scratch1/03201/jbwexler/work_dir/fmriprep/ds002734_sub-02/fmriprep_22_0_wf/single_subject_02_wf/anat_preproc_wf/surface_recon_wf/autorecon_resume_wf/parcstats/mapflow/_parcstats0
> 
> Node inputs:
> 
> FLAIR_file = <undefined>
> T1_files = <undefined>
> T2_file = <undefined>
> args = <undefined>
> big_ventricles = <undefined>
> brainstem = <undefined>
> directive = autorecon-hemi
> environ = {}
> expert = <undefined>
> flags = ['-nohyporelabel']
> hemi = lh
> hippocampal_subfields_T1 = <undefined>
> hippocampal_subfields_T2 = <undefined>
> hires = <undefined>
> mprage = <undefined>
> mri_aparc2aseg = <undefined>
> mri_ca_label = <undefined>
> mri_ca_normalize = <undefined>
> mri_ca_register = <undefined>
> mri_edit_wm_with_aseg = <undefined>
> mri_em_register = <undefined>
> mri_fill = <undefined>
> mri_mask = <undefined>
> mri_normalize = <undefined>
> mri_pretess = <undefined>
> mri_remove_neck = <undefined>
> mri_segment = <undefined>
> mri_segstats = <undefined>
> mri_tessellate = <undefined>
> mri_watershed = <undefined>
> mris_anatomical_stats = <undefined>
> mris_ca_label = <undefined>
> mris_fix_topology = <undefined>
> mris_inflate = <undefined>
> mris_make_surfaces = <undefined>
> mris_register = <undefined>
> mris_smooth = <undefined>
> mris_sphere = <undefined>
> mris_surf2vol = <undefined>
> mrisp_paint = <undefined>
> openmp = 7
> parallel = <undefined>
> steps = <undefined>
> subject_id = sub-02
> subjects_dir = /scratch1/03201/jbwexler/openneuro_derivatives/derivatives/fmriprep/ds002734-fmriprep/sourcedata/freesurfer
> talairach = <undefined>
> use_FLAIR = <undefined>
> use_T2 = <undefined>
> xopts = <undefined>
> 
> Traceback (most recent call last):
>   File "/opt/conda/lib/python3.9/site-packages/nipype/pipeline/plugins/multiproc.py", line 67, in run_node
>     result["result"] = node.run(updatehash=updatehash)
>   File "/opt/conda/lib/python3.9/site-packages/nipype/pipeline/engine/nodes.py", line 524, in run
>     result = self._run_interface(execute=True)
>   File "/opt/conda/lib/python3.9/site-packages/nipype/pipeline/engine/nodes.py", line 642, in _run_interface
>     return self._run_command(execute)
>   File "/opt/conda/lib/python3.9/site-packages/nipype/pipeline/engine/nodes.py", line 750, in _run_command
>     raise NodeExecutionError(
> nipype.pipeline.engine.nodes.NodeExecutionError: Exception raised while executing Node _parcstats0.
> 
> RuntimeError: subprocess exited with code 1.

**Comment by jbwexler** [comment]
Hmm, recon-all.log says it finished without error. I do still have access to the working directories so I'll try that workaround.

Also, I noticed the following in the stderr file, not sure if it could somehow be related:

> Matplotlib created a temporary config/cache directory at /tmp/matplotlib-ricv24z5 because the default path (/home/fmriprep/.config/matplotlib) is not a writable directory; it is highly recommended to set the MPLCONFIGDIR environment variable to a writable directory, in particular to speed up the import of Matplotlib and to better support multiprocessing.
> Fontconfig error: No writable cache directories
> Fontconfig error: No writable cache directories
> Fontconfig error: No writable cache directories
> Fontconfig error: No writable cache directories
> Fontconfig error: No writable cache directories
> Fontconfig error: No writable cache directories
> Fontconfig error: No writable cache directories
> Fontconfig error: No writable cache directories
> Fontconfig error: No writable cache directories

**Comment by mgxd** [comment]
Not related - I think https://github.com/nipreps/smriprep/pull/298 should fix the issue

**Comment by jbwexler** [comment]
Awesome - any idea how long until the next fmriprep version that includes this will be released?

**Comment by mgxd** [comment]
@jbwexler we need to verify the reason for the crashes first - can you try following the debug instructions in https://github.com/poldracklab/tacc-openneuro/issues/23#issuecomment-1219605095 and report back?

**Comment by jbwexler** [comment]
Just ran it, got this error:

> 
> -------------------------------------------------------------------------
> ERROR: Label FG1.mpm.vpnl does not exist in SUBJECTS_DIR fsaverage!
>        The fsaverage link probably points to an older freesurfer version
> -------------------------------------------------------------------------
> Linux c206-012.frontera.tacc.utexas.edu 3.10.0-1160.45.1.el7.x86_64 #1 SMP Wed Oct 13 17:20:51 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
> 
> recon-all -s sub-02 exited with ERRORS at Mon Aug 22 15:02:02 CDT 2022
> 
> For more details, see the log file /scratch1/03201/jbwexler/openneuro_derivatives/derivatives/fmriprep/ds002734-fmriprep/sourcedata/freesurfer/sub-02/scripts/recon-all-lh.log
> To report a problem, see http://surfer.nmr.mgh.harvard.edu/fswiki/BugReporting

I can share the entire output if that would be useful. Btw, have the fsaverage and fsaverage5 directories changed at all since the previous version? I copy those in prior to running to avoid some weird issues I was having - if they've changed and I'm using the old ones, that could be the issue.

**Comment by effigies** [comment]
Yes, the fsaverage in v7 is different from v6. If you just remove the `fsaverage`/`fsaverage5` directories, then fMRIPrep can copy them itself.

**Comment by jbwexler** [comment]
Awesome, will try that.

**Comment by jbwexler** [comment]
Seems to have worked! Though both the datasets I tried are now giving me "ValueError: Unknown total-readout time specification". I don't know if it's a coincidence but I seem to be seeing this error a lot recently. I'm gonna close this and we can move to https://github.com/poldracklab/tacc-openneuro/issues/20 if you have any thoughts on this.
