### ISSUE TITLE
ds000254-fmriprep: OSError: Duplicate node name "func_preproc_task_bilateralfingertapping_echo_1_wf" found.

### ISSUE THREAD

**Issue by jbwexler** [poldracklab/tacc-openneuro#24]
This showed up in all the stderr files for ds000254. 

> Matplotlib created a temporary config/cache directory at /tmp/matplotlib-ktj6ea9p because the default path (/home/fmriprep/.config/matplotlib) is not a writable directory; it is highly recommended to set the MPLCONFIGDIR environment variable to a writable directory, in particular to speed up the import of Matplotlib and to better support multiprocessing.
> Fontconfig error: No writable cache directories
> Fontconfig error: No writable cache directories
> Fontconfig error: No writable cache directories
> Fontconfig error: No writable cache directories
> Fontconfig error: No writable cache directories
> Fontconfig error: No writable cache directories
> Fontconfig error: No writable cache directories
> Fontconfig error: No writable cache directories
> Fontconfig error: No writable cache directories
> Process Process-2:
> Traceback (most recent call last):
>   File "/opt/conda/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
>     self.run()
>   File "/opt/conda/lib/python3.9/multiprocessing/process.py", line 108, in run
>     self._target(*self._args, **self._kwargs)
>   File "/opt/conda/lib/python3.9/site-packages/fmriprep/cli/workflow.py", line 118, in build_workflow
>     retval["workflow"] = init_fmriprep_wf()
>   File "/opt/conda/lib/python3.9/site-packages/fmriprep/workflows/base.py", line 89, in init_fmriprep_wf
>     single_subject_wf = init_single_subject_wf(subject_id)
>   File "/opt/conda/lib/python3.9/site-packages/fmriprep/workflows/base.py", line 379, in init_single_subject_wf
>     workflow.connect([
>   File "/opt/conda/lib/python3.9/site-packages/nipype/pipeline/engine/workflows.py", line 161, in connect
>     self._check_nodes(newnodes)
>   File "/opt/conda/lib/python3.9/site-packages/nipype/pipeline/engine/workflows.py", line 769, in _check_nodes
>     raise IOError('Duplicate node name "%s" found.' % node.name)
> OSError: Duplicate node name "func_preproc_task_bilateralfingertapping_echo_1_wf" found.

**Comment by effigies** [comment]
Almost certainly both nii and nii.gz files for the same task.

**Comment by effigies** [comment]
This dataset contains a copy of itself nested inside it. We should delete and re-release.

https://openneuro.org/datasets/ds000254/versions/00002

**Comment by jbwexler** [comment]
Just deleted nested version and released new snapshot: https://openneuro.org/datasets/ds000254/versions/1.0.0
