### ISSUE TITLE
ds002843-mriqc: "Can't use dataset with < 5 time points per voxel!"

### ISSUE THREAD

**Issue by jbwexler** [poldracklab/tacc-openneuro#58]
Only for sub-dmp1095

> Node: mriqc_wf.funcMRIQC.ComputeIQMs.outliers
> Working directory: /scratch1/03201/jbwexler/work_dir/mriqc/ds002843_sub-dmp1095/mriqc_wf/funcMRIQC/ComputeIQMs/_in_file_..scratch1..03201..jbwexler..openneuro_derivatives..derivatives..mriqc..ds002843-mriqc..sourcedata..raw..sub-dmp1095..ses-scan1..func..sub-dmp1095_ses-scan1_task-risk_run-4_bold.nii.gz/outliers
> 
> Node inputs:
> 
> args = <undefined>
> autoclip = False
> automask = False
> environ = {}
> fraction = True
> in_file = /scratch1/03201/jbwexler/work_dir/mriqc/ds002843_sub-dmp1095/mriqc_wf/funcMRIQC/fMRI_HMC/_in_file_..scratch1..03201..jbwexler..openneuro_derivatives..derivatives..mriqc..ds002843-mriqc..sourcedata..raw..sub-dmp1095..ses-scan1..func..sub-dmp1095_ses-scan1_task-risk_run-4_bold.nii.gz/motion_correct/sub-dmp1095_ses-scan1_task-risk_run-4_bold_valid_volreg.nii.gz
> interval = False
> legendre = False
> mask = /scratch1/03201/jbwexler/work_dir/mriqc/ds002843_sub-dmp1095/mriqc_wf/funcMRIQC/fMRIBrainMask/_in_file_..scratch1..03201..jbwexler..openneuro_derivatives..derivatives..mriqc..ds002843-mriqc..sourcedata..raw..sub-dmp1095..ses-scan1..func..sub-dmp1095_ses-scan1_task-risk_run-4_bold.nii.gz/afni_msk/sub-dmp1095_ses-scan1_task-risk_run-4_bold_valid_volreg_tstat_mask.nii.gz
> out_file = outliers.out
> outliers_file = <undefined>
> polort = <undefined>
> qthr = 0.001
> save_outliers = False
> 
> Traceback (most recent call last):
>   File "/opt/conda/lib/python3.8/site-packages/nipype/pipeline/plugins/multiproc.py", line 67, in run_node
>     result["result"] = node.run(updatehash=updatehash)
>   File "/opt/conda/lib/python3.8/site-packages/nipype/pipeline/engine/nodes.py", line 516, in run
>     result = self._run_interface(execute=True)
>   File "/opt/conda/lib/python3.8/site-packages/nipype/pipeline/engine/nodes.py", line 635, in _run_interface
>     return self._run_command(execute)
>   File "/opt/conda/lib/python3.8/site-packages/nipype/pipeline/engine/nodes.py", line 741, in _run_command
>     result = self._interface.run(cwd=outdir)
>   File "/opt/conda/lib/python3.8/site-packages/nipype/interfaces/base/core.py", line 428, in run
>     runtime = self._run_interface(runtime)
>   File "/opt/conda/lib/python3.8/site-packages/nipype/interfaces/afni/preprocess.py", line 1840, in _run_interface
>     runtime = super(OutlierCount, self)._run_interface(
>   File "/opt/conda/lib/python3.8/site-packages/nipype/interfaces/base/core.py", line 822, in _run_interface
>     self.raise_exception(runtime)
>   File "/opt/conda/lib/python3.8/site-packages/nipype/interfaces/base/core.py", line 749, in raise_exception
>     raise RuntimeError(
> RuntimeError: Command:
> 3dToutcount -fraction -mask /scratch1/03201/jbwexler/work_dir/mriqc/ds002843_sub-dmp1095/mriqc_wf/funcMRIQC/fMRIBrainMask/_in_file_..scratch1..03201..jbwexler..openneuro_derivatives..derivatives..mriqc..ds002843-mriqc..sourcedata..raw..sub-dmp1095..ses-scan1..func..sub-dmp1095_ses-scan1_task-risk_run-4_bold.nii.gz/afni_msk/sub-dmp1095_ses-scan1_task-risk_run-4_bold_valid_volreg_tstat_mask.nii.gz -qthr 0.00100 /scratch1/03201/jbwexler/work_dir/mriqc/ds002843_sub-dmp1095/mriqc_wf/funcMRIQC/fMRI_HMC/_in_file_..scratch1..03201..jbwexler..openneuro_derivatives..derivatives..mriqc..ds002843-mriqc..sourcedata..raw..sub-dmp1095..ses-scan1..func..sub-dmp1095_ses-scan1_task-risk_run-4_bold.nii.gz/motion_correct/sub-dmp1095_ses-scan1_task-risk_run-4_bold_valid_volreg.nii.gz
> Standard output:
> 
> Standard error:
> ++ 3dToutcount: AFNI version=AFNI_21.2.06 (Sep  1 2021) [64-bit]
> ESC[7m*+ WARNING:ESC[0m   If you are performing spatial transformations on an oblique dset,
>   such as /scratch1/03201/jbwexler/work_dir/mriqc/ds002843_sub-dmp1095/mriqc_wf/funcMRIQC/fMRIBrainMask/_in_file_..scratch1..03201..jbwexler..openneuro_derivatives..derivatives..mriqc..ds002843-mriqc..sourcedata..raw..sub-dmp1095..ses-scan1..func..sub-dmp1095_ses-scan1_task-risk_run-4_bold.nii.gz/afni_msk/sub-dmp1095_ses-scan1_task-risk_run-4_bold_valid_volreg_tstat_mask.nii.gz,
>   or viewing/combining it with volumes of differing obliquity,
>   you should consider running:
>      3dWarp -deoblique
>   on this and  other oblique datasets in the same session.
>  See 3dWarp -help for details.
> ++ Oblique dataset:/scratch1/03201/jbwexler/work_dir/mriqc/ds002843_sub-dmp1095/mriqc_wf/funcMRIQC/fMRIBrainMask/_in_file_..scratch1..03201..jbwexler..openneuro_derivatives..derivatives..mriqc..ds002843-mriqc..sourcedata..raw..sub-dmp1095..ses-scan1..func..sub-dmp1095_ses-scan1_task-risk_run-4_bold.nii.gz/afni_msk/sub-dmp1095_ses-scan1_task-risk_run-4_bold_valid_volreg_tstat_mask.nii.gz is 27.800009 degrees from plumb.
> ++ 53546 voxels in the mask
> ++ Oblique dataset:/scratch1/03201/jbwexler/work_dir/mriqc/ds002843_sub-dmp1095/mriqc_wf/funcMRIQC/fMRI_HMC/_in_file_..scratch1..03201..jbwexler..openneuro_derivatives..derivatives..mriqc..ds002843-mriqc..sourcedata..raw..sub-dmp1095..ses-scan1..func..sub-dmp1095_ses-scan1_task-risk_run-4_bold.nii.gz/motion_correct/sub-dmp1095_ses-scan1_task-risk_run-4_bold_valid_volreg.nii.gz is 27.800009 degrees from plumb.
> ** Can't use dataset with < 5 time points per voxel!
> Return code: 1

**Comment by effigies** [comment]
Clearly a prematurely terminated run.

```
$ nib-ls sub-dmp1095/ses-scan1/func/sub-dmp1095_ses-scan1_task-risk_run-*.nii.gz
sub-dmp1095/ses-scan1/func/sub-dmp1095_ses-scan1_task-risk_run-1_bold.nii.gz int16 [ 64,  64,  53, 104] 3.00x3.00x3.00x3.00   sform
sub-dmp1095/ses-scan1/func/sub-dmp1095_ses-scan1_task-risk_run-2_bold.nii.gz int16 [ 64,  64,  53, 104] 3.00x3.00x3.00x3.00   sform
sub-dmp1095/ses-scan1/func/sub-dmp1095_ses-scan1_task-risk_run-3_bold.nii.gz int16 [ 64,  64,  53, 104] 3.00x3.00x3.00x3.00   sform
sub-dmp1095/ses-scan1/func/sub-dmp1095_ses-scan1_task-risk_run-4_bold.nii.gz int16 [ 64,  64,  53,   4] 3.00x3.00x3.00x3.00   sform
```

We should probably just remove it before running fmriprep/mriqc.

**Comment by jbwexler** [comment]
Oh sorry forgot to mention this was an old version of MRIQC, v21.0.0rc2. Is it worth a rerun to see if this has been fixed?

**Comment by effigies** [comment]
I suspect nothing has changed. It's just a bad run, probably a subject who decided they couldn't take another full run. We should just drop it. I've created an issue for mriqc simply to ignore such short files.
