### ISSUE TITLE
ds003604-fmriprep: "ValueError: A fieldmap or phase-difference estimation type was found, but an anatomical reference (magnitude1 file) is missing."

### ISSUE THREAD

**Issue by jbwexler** [poldracklab/tacc-openneuro#61]
As the error says, the fieldmap directories simply contain phasediff files and nothing else. I'm guessing the easiest solution here is just to .bidsignore the fieldmap directories?

**Comment by effigies** [comment]
This will be fixed in 23.0.1.

**Comment by jbwexler** [comment]
Hmmm I ran with 23.0.1 and it didn't seem to fix the issue.

**Comment by effigies** [comment]
Reproduced. Will open an issue on sdcflows.

**Comment by jbwexler** [comment]
Seems to have been resolved with 23.0.2
