### ISSUE TITLE
Note version of software run in README

### ISSUE THREAD

**Issue by effigies** [poldracklab/tacc-openneuro#64]
While accessible through `dataset_description.json`, it would be good to mention the version of fMRIPrep/MRIQC run directly in the README. This could be done while setting up the run or as a post-processing step, pulling information out of `dataset_description.json`.

**Comment by jbwexler** [comment]
Done https://github.com/poldracklab/tacc-openneuro/commit/0553485d88db4e543c028684cc9f153b06a1c947
