### ISSUE TITLE
ds002837-fmriprep: ICA-AROMA issues

### ISSUE THREAD

**Issue by jbwexler** [poldracklab/tacc-openneuro#69]
For majority of subjects (only 19 out of 86 were successful):

> Node: fmriprep_23_0_wf.single_subject_5_wf.func_preproc_task_500daysofsummer_run_01_wf.ica_aroma_wf.ica_aroma
> Working directory: /scratch1/03201/jbwexler/work_dir/fmriprep/ds002837_sub-5/fmriprep_23_0_wf/single_subject_5_wf/func_preproc_task_500daysofsummer_run_01_wf/ica_aroma_wf/ica_aroma
> 
> Node inputs:
> 
> TR = 1.0
> args = -np
> compress_report = auto
> denoise_type = nonaggr
> dim = <undefined>
> environ = {}
> feat_dir = <undefined>
> fnirt_warp_file = <undefined>
> in_file = <undefined>
> mask = <undefined>
> mat_file = <undefined>
> melodic_dir = <undefined>
> motion_parameters = <undefined>
> out_dir = out
> out_report = ica_aroma_reportlet.svg
> report_mask = <undefined>
> 
> Traceback (most recent call last):
>   File "/opt/conda/lib/python3.9/site-packages/nipype/pipeline/plugins/multiproc.py", line 67, in run_node
>     result["result"] = node.run(updatehash=updatehash)
>   File "/opt/conda/lib/python3.9/site-packages/nipype/pipeline/engine/nodes.py", line 527, in run
>     result = self._run_interface(execute=True)
>   File "/opt/conda/lib/python3.9/site-packages/nipype/pipeline/engine/nodes.py", line 645, in _run_interface
>     return self._run_command(execute)
>   File "/opt/conda/lib/python3.9/site-packages/nipype/pipeline/engine/nodes.py", line 771, in _run_command
>     raise NodeExecutionError(msg)
> nipype.pipeline.engine.nodes.NodeExecutionError: Exception raised while executing Node ica_aroma.
> 
> Cmdline:
>         ICA_AROMA.py -tr 1.000 -np -den nonaggr -i /scratch1/03201/jbwexler/work_dir/fmriprep/ds002837_sub-5/fmriprep_23_0_wf/single_subject_5_wf/func_preproc_task_500daysofsummer_run_01_wf/ica_aroma_wf/smooth/vol0000_xform-00000_clipped_merged_smooth.nii.gz -m /scratch1/03201/jbwexler/work_dir/fmriprep/ds002837_sub-5/fmriprep_23_0_wf/single_subject_5_wf/func_preproc_task_500daysofsummer_run_01_wf/bold_std_trans_wf/_std_target_MNI152NLin6Asym.res2/mask_std_tfm/vol0000_unwarped_merged_valid_average_corrected_brain_mask_maths_trans.nii.gz -meldir /scratch1/03201/jbwexler/work_dir/fmriprep/ds002837_sub-5/fmriprep_23_0_wf/single_subject_5_wf/func_preproc_task_500daysofsummer_run_01_wf/ica_aroma_wf/melodic -mc /scratch1/03201/jbwexler/work_dir/fmriprep/ds002837_sub-5/fmriprep_23_0_wf/single_subject_5_wf/func_preproc_task_500daysofsummer_run_01_wf/bold_hmc_wf/normalize_motion/motion_params.txt -o /scratch1/03201/jbwexler/work_dir/fmriprep/ds002837_sub-5/fmriprep_23_0_wf/single_subject_5_wf/func_preproc_task_500daysofsummer_run_01_wf/ica_aroma_wf/ica_aroma/out
> Stdout:
> 
>         ------------------------------- RUNNING ICA-AROMA -------------------------------
>         --------------- 'ICA-based Automatic Removal Of Motion Artifacts' ---------------
> 
>         Warning! Please check whether the determined TR (of 1.0s) is correct!
> 
>         Step 1) MELODIC
>           - The existing/specified MELODIC directory will be used.
>         Step 2) Automatic classification of the components
>           - registering the spatial maps to MNI
>           - extracting the CSF & Edge fraction features
>           - extracting the Maximum RP correlation feature
>           - extracting the High-frequency content feature
>           - classification
>         Step 3) Data denoising
> 
>         ----------------------------------- Finished -----------------------------------
> 
> Stderr:
>         Image Exception : #99 :: Out of memory
>         Out of memory
> Traceback:
>         Traceback (most recent call last):
>           File "/opt/conda/lib/python3.9/site-packages/nipype/interfaces/base/core.py", line 453, in aggregate_outputs
>             setattr(outputs, key, val)
>           File "/opt/conda/lib/python3.9/site-packages/nipype/interfaces/base/traits_extension.py", line 330, in validate
>             value = super(File, self).validate(objekt, name, value, return_pathlike=True)
>           File "/opt/conda/lib/python3.9/site-packages/nipype/interfaces/base/traits_extension.py", line 135, in validate
>             self.error(objekt, name, str(value))
>           File "/opt/conda/lib/python3.9/site-packages/traits/base_trait_handler.py", line 74, in error
>             raise TraitError(
>         traits.trait_errors.TraitError: The 'nonaggr_denoised_file' trait of a _ICA_AROMAOutputSpecRPT instance must be a pathlike object or string
>  representing an existing file, but a value of '/scratch1/03201/jbwexler/work_dir/fmriprep/ds002837_sub-5/fmriprep_23_0_wf/single_subject_5_wf/func
> _preproc_task_500daysofsummer_run_01_wf/ica_aroma_wf/ica_aroma/out/denoised_func_data_nonaggr.nii.gz' <class 'str'> was specified.
> 
>         During handling of the above exception, another exception occurred:
> 
>         Traceback (most recent call last):
>           File "/opt/conda/lib/python3.9/site-packages/nipype/interfaces/base/core.py", line 398, in run
>             runtime = self._post_run_hook(runtime)
>           File "/opt/conda/lib/python3.9/site-packages/niworkflows/interfaces/reportlets/segmentation.py", line 231, in _post_run_hook
>             outputs = self.aggregate_outputs(runtime=runtime)
>           File "/opt/conda/lib/python3.9/site-packages/nipype/interfaces/base/core.py", line 460, in aggregate_outputs
>             raise FileNotFoundError(msg)
>         FileNotFoundError: No such file or directory '/scratch1/03201/jbwexler/work_dir/fmriprep/ds002837_sub-5/fmriprep_23_0_wf/single_subject_5_wf/func_preproc_task_500daysofsummer_run_01_wf/ica_aroma_wf/ica_aroma/out/denoised_func_data_nonaggr.nii.gz' for output 'nonaggr_denoised_file' of a ICA_AROMARPT interface

**Comment by effigies** [comment]
> ```
> Image Exception : #99 :: Out of memory
> Out of memory
> ```

All there is to do there is rerun or simply not run ICA-AROMA.

**Comment by jbwexler** [comment]
Sounds good. So you don't think "Warning! Please check whether the determined TR (of 1.0s) is correct!" is an issue?

**Comment by effigies** [comment]
Unlikely. I think it comes from a time when 1s TR was very fast so likely indicative of an error. This is movie-watching, so they're going for "big", and so a short TR is plausible.

**Comment by jbwexler** [comment]
Running without ica-aroma solved this.
