### ISSUE TITLE
ds001555-fmriprep (minimal mode):  "mritotal: Command not found."

### ISSUE THREAD

**Issue by jbwexler** [poldracklab/tacc-openneuro#76]
For 2/3 subjects from a sample run of ds001555:

>         mritotal -verbose -debug -clobber -modeldir /opt/freesurfer/mni/bin/../share/mni_autoreg -protocol icbm transforms/tmp.talairach.158285/src.mnc transforms/talairach.auto.xfm
>         mritotal: Command not found.
>         ERROR: mritotal failed, see transforms/talairach.log
transforms/talairach.log:
> /scratch1/03201/jbwexler/openneuro_derivatives/derivatives/fmriprep/ds001555-fmriprep/sourcedata/freesurfer/sub-001/mri
> /opt/freesurfer/bin/talairach
> --i orig_nu.mgz --xfm transforms/talairach.auto.xfm
> talairach 7.3.2
> Linux c210-012.frontera.tacc.utexas.edu 3.10.0-1160.90.1.el7.x86_64 #1 SMP Thu May 4 15:21:22 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
> Fri Aug 25 02:18:23 UTC 2023
> tmpdir is transforms/tmp.talairach.173159
> /scratch1/03201/jbwexler/openneuro_derivatives/derivatives/fmriprep/ds001555-fmriprep/sourcedata/freesurfer/sub-001/mri
> mri_convert orig_nu.mgz transforms/tmp.talairach.173159/src.mnc
> mri_convert orig_nu.mgz transforms/tmp.talairach.173159/src.mnc
> reading from orig_nu.mgz...
> TR=0.00, TE=0.00, TI=0.00, flip angle=0.00
> i_ras = (-1, 0, 0)
> j_ras = (0, 0, -1)
> k_ras = (0, 1, 0)
> writing to transforms/tmp.talairach.173159/src.mnc...

**Comment by effigies** [comment]
Recently got a fix in. Will update the docker image this week.
