### ISSUE TITLE
ds000102 fmriprep:  ValueError: space identifier "MNI152NLin2009cAsym" is invalid.

### ISSUE THREAD

**Issue by jbwexler** [poldracklab/tacc-openneuro#9]
I'm getting the following error for every subject in ds000102. Oddly, I didn't get it in another dataset running simultaneously. I first ran into this while using fmriprep v21.0.1 and then tried upgrading to v21.0.2, which didn't solve the problem. Here's an example command:
`code/containers/scripts/singularity_cmd run --cleanenv code/containers/images/bids/bids-fmriprep--21.0.1.sing sourcedata/raw /scratch1/03201/jbwexler/openneuro_derivatives/derivatives/fmriprep/ds000102-fmriprep participant --participant-label '04' -w '/scratch1/03201/jbwexler/work_dir/fmriprep//ds000102_sub-04' -vv --output-spaces MNI152NLin2009cAsym:res-2 anat func fsaverage5 --nthreads 14 --omp-nthreads 7 --skip-bids-validation --notrack --fs-license-file /home1/03201/jbwexler/.freesurfer.txt --use-aroma --ignore slicetiming --output-layout bids --cifti-output --resource-monitor --skull-strip-t1w force --mem_mb 37500 --bids-database-dir /tmp --md-only-boilerplate --use-syn-sdc warn`

> Traceback (most recent call last):
>   File "/opt/conda/bin/fmriprep", line 8, in <module>
>     sys.exit(main())
>   File "/opt/conda/lib/python3.8/site-packages/fmriprep/cli/run.py", line 38, in main
>     parse_args()
>   File "/opt/conda/lib/python3.8/site-packages/fmriprep/cli/parser.py", line 671, in parse_args
>     opts = parser.parse_args(args, namespace)
>   File "/opt/conda/lib/python3.8/argparse.py", line 1768, in parse_args
>     args, argv = self.parse_known_args(args, namespace)
>   File "/opt/conda/lib/python3.8/argparse.py", line 1800, in parse_known_args
>     namespace, args = self._parse_known_args(args, namespace)
>   File "/opt/conda/lib/python3.8/argparse.py", line 2006, in _parse_known_args
>     start_index = consume_optional(start_index)
>   File "/opt/conda/lib/python3.8/argparse.py", line 1946, in consume_optional
>     take_action(action, args, option_string)
>   File "/opt/conda/lib/python3.8/argparse.py", line 1874, in take_action
>     action(self, namespace, argument_values, option_string)
>   File "/opt/conda/lib/python3.8/site-packages/niworkflows/utils/spaces.py", line 708, in __call__
>     for sp in Reference.from_string(val):
>   File "/opt/conda/lib/python3.8/site-packages/niworkflows/utils/spaces.py", line 336, in from_string
>     return [cls(_args[0], s) for s in allspecs]
>   File "/opt/conda/lib/python3.8/site-packages/niworkflows/utils/spaces.py", line 336, in <listcomp>
>     return [cls(_args[0], s) for s in allspecs]
>   File "<attrs generated init niworkflows.utils.spaces.Reference>", line 11, in __init__
>   File "/opt/conda/lib/python3.8/site-packages/niworkflows/utils/spaces.py", line 246, in _check_name
>     raise ValueError(
> ValueError: space identifier "MNI152NLin2009cAsym" is invalid.
> Valid identifiers are: T1w, T2w, anat, fsnative, func, run, sbref, session, individual, dwi

**Comment by effigies** [comment]
Seems like a templateflow issue. Is `SINGULARITYENV_TEMPLATEFLOW_HOME` (or whatever the correct variable is called) set and the directory populated?

**Comment by jbwexler** [comment]
Thanks for the tip - seems the templateflow subdataset wasn't installed properly. Rerunning now.
